Actualizada PostCard y ReviewCard. Agregada la imagen profile.png (im…
luigi3357/Pet-Care pull request #14
Opened 2022-03-02 21:48 UTC by jparaducha

Actualizada PostCard y ReviewCard. Agregada la imagen profile.png (imagen de perfil que se muestra por defecto en las cards

2022-03-02 22:44 UTC, julio-hdz requested changes
@jparaducha me aparece que tu branch esta desactualizada respecto a development. Fijate de lanzar un pull origin a ver

2022-03-02 23:12 UTC, jsguerra07 submitted a review, later dismissed

2022-03-03 00:00 UTC, julio-hdz approved these changes

2022-03-03 01:24 UTC, luigi3357 approved these changes

2022-03-03 01:25 UTC, merged